---
header-includes:
   - \usepackage[document]{ragged2e}
   - \usepackage{hyperref}
   - \usepackage{polyglossia}
   - \usepackage{fourier-otf}
   - \usepackage{leading}
   - \newfontfamily\hebrewfont{Shlomo semiStam}
   - \let\hebrewfonttt\ttfamily
   - \setdefaultlanguage{english}
   - \setotherlanguage{hebrew}
   - \usepackage{graphicx}
output:
  pdf_document:
     latex_engine: xelatex
     keep_tex: true
     number_sections: yes
     highlight: NULL
classoption: a4paper
fontsize: 12pt
---


\begin{hebrew}

\resizebox{159mm}{!}{\textbf{דברי הנעצב וצעיר יהודה אריה ממודינא לקורא}}
\center
\resizebox{!}{8mm}{\textbf{רוב שלו'}}





\fontsize{5mm}{5.5mm}\selectfont
\justify



כתב החכם דון גדליה יחיא זל בספר שלשלת הקבלה שלו בדור סמ"ג והרמבן דף  נ"ו כבדברי' האלה, וקבלתי שהיה להרמבן תלמיד א' שהיה שמו ר' אבנר ויסת אותו רוח שעשועים ונעשה $\overline{\mbox{צדוקי}}$ ומזלו גרם שעלה במעלות ויהי נורא בכל הארץ, אחרי הימים ביום צ"ב שלח והביא לפניו הרמבן רבו ובפניו הוא בעצמו הרג חזיר א' וינתחהו ויבשלהו ויאכלהו, ואחרי  אכלו שאל אל הרב על כמה כריתות  עבר והשיב הרב שהיו ד' והוא אמר שהיו ה' נהיה רוצה לחלוק עם רבו והרב נתן עיניו בו דרך כעס ויאלם  האיש כי עדין נשארה עליו מעט יראה מאת רבו  ולבסוף שאל הרב מי הביאו אל ההמרה, והוא  השיב כי פעם אחת שמע שדרש בפרשת האזינו שהיו בפרשה ההיא כלולים כל המצות וכל הדברים  שבעולם ולהיות זה אצלו מןהנמנע והפך לאיש אחר, ויען הרב ועדין  אני  אומר זה ואשל מה שתרצה, ויתמה האיש מאר ויאמר  לו אם כן הוא  הראני  נא אם  תמצא  שמי כתוב שם ויאמ' הרמבן כן דברת מידי תבקשנו,  ותיכף הלך לו בקרן זוית ויתפלל  ויבא בפיו פסוק אמרתי  $\dot{\mbox{א}}$פיהם אש$\dot{\mbox{ב}}$יתה  מא$\dot{\mbox{נ}}$וש זכ$\dot{\mbox{ר}}$ם כי אות שלשית של  כל תבה  שם האיש $\dot{\mbox{ר}}\dot{\mbox{נ}}\dot{\mbox{ב}}\dot{\mbox{א}}$, כשמוע האיש הדבר הזה נפלו פניו וישאל לרבו אם יש תרופה  למכתו, ויאמ' הרב אתה שמעת  דברי הפסוק וילך  הרב לדרכו, ותכף האיש לקח לו ספינה בלי מלח ומשוט  ויכנס בה וילך  באשר הוליכו הרוח ולא נודע ממנו מאומה עכ"ל:


\justify
ויהי בשנת הע"א ראיתי הספר הזה בלוי וקרוע ביד כמ' יואל בר אליעזר אויד"ירץ זל שהיה נושאו  למכרו, ובראותי בסקירת עין שהיה דברי ויכוח הדת גמרתי תכך לקנותו בכל ערך שירצה וסוף  דבר קניתיהו מידו כנגד י"ב $\ddot{\mbox{ס}}$ולדין[1ב] וכאשר קראתי בו ביישוב וראיתי היותו תשובות ר' אבנר שהמיר דתו ונקרא אח"כ אלפ$\dot{\ddot{\mbox{ו}}}$נסו נתברר לי ודאי שהם דברי ר' אבנר תלמיד הרמבן זל שכתב בעל שלשת הקבלה שהבאתי לעיל, ובאמת לא היה כעת בזולת לדבר כאלה כי אם לאדם שטוב מלפניו וחכם כהיותו תלמיד רב וגדול כהרמבן זל ויין מגתו הגם $\widearc{\mbox{שאחכ}}$ החמיץ, וזה  אני  אומ' אחרי כי כל ימי גדלתי בין חכמי הנוצרים מאז היותי בן עשר שנים מתוכח בדברי הדת נער הייתי גם זקנתי בכך, עד שהעזתי מצח לומר כמה פעמים  לאחוזת מרעי ותלמידי כי בזה אינני מודה לשום א' מחכמי ישראל שהיו- מימות הרב דון יצחק אברבניל זל ועד היום הזה, ומי יתן ושמעתי לקול בני ותלמידי ורעי שהרהיבוני ובקשו ממני  כמה שנים לכתוב על ספר  בענין זה  מהדברי' אשר שם אלקים בפי לכבוד שמו חדשים לא שערום אשר קדמוני, ושרבות זמני בהלכני ועתה עד זקנה אני הוא בשנה  המסוכנת, הכל ס"ג, ואין עוד בי כח לעשות חיל כי אם העיון ההכרחי למשא עול  התורה אשר על צוארי, כי מעיד אני עלי שלא הנחתי ספר מורפס  מן הנוצרים לאט"ין איטאאליאנו ספרדי או עברי מדבר בעניני האמונה נגד היהודים שלא קראתי אותו, וכן מהיהודי נגד הנוצרים, ובכן לנו ראיתי  בין כלם מהפך דברי אלקי' חיים ומדרשי חזל למינו ורצונו בפני הראות חכמה ודעת מזה, אשר נראה שהיה פילוסוף הגיוני ותלמודי גדול מאד, וכיון שלא זכיתי לכתוב תשובה לדבריו עד היה כנזכר, גמרתי בדעתי לשרוף אותו באש קודם מותי, כי אמרתי אולי יבא ליד פתי ובלתי בקי להשיב לאפיקורוס ותטרף  דעתו בדבריו ו$\widearc{\mbox{אחכ}}$ חזרתי בי וחשבתי מי יודע יחנני ה' בחיים יעדין  אזכה לעשות כסיל לאולתו , או זולתי מן החכמי',

\makebox[\textwidth]{
ובין כך מתרה אני בכל מי שיקרא בו אם  אינו בקי ויודע בטיב
}

\makebox[\textwidth]{
הויכוחים האלה לא יאבה  לשמוט כל דברי אלה
}

\makebox[\textwidth]{
ויניח המ--- לרגיל להתוכח עם הנוצרי'
}

\makebox[\textwidth]{
אשר על מי הם תהיה תורת אמת
}

\makebox[\textwidth]{
ובכל ויכוח יתברר האמת
}

\makebox[\textwidth]{
  לכבוד ה' אלוקים אמת
}

\end{hebrew}
